// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $resultados from "./routes/resultados.tsx";
import * as $Bandas from "./islands/Bandas.tsx";
import * as $Evaluate from "./islands/Evaluate.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import * as $PirePer from "./islands/PirePer.tsx";
import * as $Results from "./islands/Results.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
    "./routes/resultados.tsx": $resultados,
  },
  islands: {
    "./islands/Bandas.tsx": $Bandas,
    "./islands/Evaluate.tsx": $Evaluate,
    "./islands/Navigation.tsx": $Navigation,
    "./islands/PirePer.tsx": $PirePer,
    "./islands/Results.tsx": $Results,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
