// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $index from "./routes/index.tsx";
import * as $Eval2ANE from "./islands/Eval2ANE.tsx";
import * as $Eval3_2ANE from "./islands/Eval3_2ANE.tsx";
import * as $Navigation from "./islands/Navigation.tsx";
import * as $Transmisor from "./islands/Transmisor.tsx";
import * as $showInfo from "./islands/showInfo.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Eval2ANE.tsx": $Eval2ANE,
    "./islands/Eval3_2ANE.tsx": $Eval3_2ANE,
    "./islands/Navigation.tsx": $Navigation,
    "./islands/Transmisor.tsx": $Transmisor,
    "./islands/showInfo.tsx": $showInfo,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
